name = "star_relay_core"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Nathan Rignall"]
maintainers = ["Nathan Rignall <rignallnathan@gmail.com>"]
maintainers-logins = ["NathanRignall"]

executables = ["star_relay_core"]
[[depends-on]]
aws = "^21.0.0"
[[depends-on]]
gnatcoll = "^21.0.0"

[environment]
DEVICE_IDENTIFIER.set = "100"
CLOUD_MULTICAST_ADDRESS.set = "239.255.128.128"