version: "3"

services:
  relay:
    image: starrelaycore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "1234:1234"
    environment:
      - DEVICE_IDENTIFIER=100
      - CLOUD_MULTICAST_ADDRESS=239.255.128.128
    networks:
      - system

networks:
  system:
    name: star_demo_core_system
    external: true